### PR TITLE
App - Improved UI

### PR DESCRIPTION
**Pull request by DunkleMango**
+ checkboxes get cleared when the user completes a corresponding action
+ now only the steam directory needs to be selected (no sub-paths to workshop and game/mods)
+ updated visual-flow (user works from top to bottom)

### CODE REVIEW

**Comment by DunkleMango** [comment]
Here is the latest version of the application.
You can take a look if you want.
I would like to make this the next release version.

[StarboundModManager.zip](https://github.com/DunkleMango/StarboundModManager/files/3469465/StarboundModManager.zip)

**Comment by AbsolofDarkness** [comment]
I am not sure if this is just a problem on my end, but I am getting a JNI error when I launch it.

**Comment by DunkleMango** [comment]
Okay, on my end everything works fine.
What error do you get? Could you post a detailed error-log here?
A JNI error usually means that something with the Java installation is wrong.
What Java Version are you using?

**Comment by AbsolofDarkness** [comment]
I didn't see any log created, if it's supposed to create the log in the same folder as the executable. As for the Java version, this is what the console says
java version "1.8.0_211"
Java SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot 64-Bit Server VM (build 25.211-b12, mixed mode)
If you need I can send a screen video of what happens when I try to launch the application.

**Comment by DunkleMango** [comment]
> java version "1.8.0_211"

And that's the issue here. The app was compiled for java12 with openjfx.
I'll need to do a backport for version 1.8.
But that was my intention anyways, since 1.8 is still the most commonly used version.
I will post the backported jar here, when I'm done.

**Comment by DunkleMango** [comment]
Here is the backported version for java 8.
It should be easier to upgrade to newer versions in the future.
The jar will now be delivered, built on java 8, with support for java 12 environments.

It would be nice if you could test the loading times of the application.
The caching should make the startup way faster in comparison toon the first load.

[StarboundModManager.zip](https://github.com/DunkleMango/StarboundModManager/files/3501519/StarboundModManager.zip)

**Comment by AbsolofDarkness** [comment]
Alright, will do once I get on later today.

**Comment by AbsolofDarkness** [comment]
It seems to work great with displaying the mods. I'd recommend making the window larger though, as some mods, at least on my end, are long, so I have to scroll to click the checkbox.

**Comment by DunkleMango** [comment]
Good point, I'll probably just add linebreaks in there. That should do the trick. 😄

**Comment by DunkleMango** [comment]
It should be better now. What do you think?

grafik

**Comment by DunkleMango** [comment]
Forgot to upload the new jar, whoops.
Here you go: 
📦 [StarboundModManager.zip](https://github.com/DunkleMango/StarboundModManager/files/3512188/StarboundModManager.zip)

**Comment by AbsolofDarkness** [comment]
So I tried launching, and nothing showed. I ran it through the console, and get an error

Exception in thread "JavaFX Application Thread" Exception in thread "main" java.lang.NoClassDefFoundError

I also saw this

at com.github.dunklemango.starboundmodmanager.MainFrame.<clinit>(MainFrame.java:44)

I think it created a log, so I can send that if needed.

**Comment by DunkleMango** [comment]
Okay, found the issue: the libraries were not added to the classpath.
I will have to work on that next.
For now, I'll just give you a new .zip with the libs attached. Worked for me.

📦 [StarboundModManager_with_libs.zip](https://github.com/DunkleMango/StarboundModManager/files/3513570/StarboundModManager_with_libs.zip)

**Comment by AbsolofDarkness** [comment]
Works good! Though it seems to not transfer mods. There's a quick popup that instantly disappears, and then nothing happens. dunno if it's just something on my end or not.

**Comment by AbsolofDarkness** [comment]
https://drive.google.com/file/d/1QkANSRnr-VFMpib26vE_RGeSWKT_0EzE/view?usp=sharing

Here's a desktop recording of what happens.

**Comment by DunkleMango** [comment]
Okay, I'll have a look at that as well.
For now, you can try to run it via command prompt.
The logger should print out all files that were not transfered correctly with the corresponding error. :)

**Comment by DunkleMango** [comment]
Sorry for taking so long to respond. 😅 
I am pretty busy with preparations for my upcoming exams atm.

The problem with the files not being transfered has been corrected and the libs are now being packed inside the jar like they used to.
The log will also show a few more details now.

📦  [StarboundModManager.zip](https://github.com/DunkleMango/StarboundModManager/files/3562640/StarboundModManager.zip)

**Comment by DunkleMango** [comment]
I found a bug with the workshop-item-caching.
If the app won't show and just shuts down with an error, that probably means it was that bug.
Sometimes on load and store of workshop-data, if there are special characters in UTF-8 encoding (like russian/cyrillic letters), the bug will duplicate those letters X times and it gets worse per session, resulting in a gigantic file with around 300 MB.
That is the moment, when the app can't load it into memory anymore.

If that happens just delete the `workshopCache.json` file in your user directory for now.

I'll look into this.

**Pull request merged**
